<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_13,37</name>
   <tag></tag>
   <elementGuidId>bf4068ee-e803-4546-a677-8edef092bd3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@aria-label,'Cart')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.minicart-total.d-block.d-md-none > div.minicart-wrapper.col-icon-cart > div.target-wrap > span.minicart-grandtotal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4bf57419-4a5a-40df-99a5-06cdef6c5bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>minicart-grandtotal</value>
      <webElementGuid>0ec743dd-3c62-40f6-8af0-d790d4895751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>€13,37</value>
      <webElementGuid>6f15ad67-6443-4fd7-9ca8-af8692d7a582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brand-header&quot;)/nav[@class=&quot;nav-wrapper col-nav-wrapper&quot;]/div[@class=&quot;sticky-element navigation-shadows is-sticky&quot;]/div[@class=&quot;header-wrapper container-fluid container-margin d-flex align-items-center justify-content-between&quot;]/div[@class=&quot;user-util d-flex align-items-center&quot;]/div[@class=&quot;minicart col-minicart&quot;]/div[@class=&quot;minicart-total d-block d-md-none&quot;]/div[@class=&quot;minicart-wrapper col-icon-cart&quot;]/div[@class=&quot;target-wrap&quot;]/span[@class=&quot;minicart-grandtotal&quot;]</value>
      <webElementGuid>5c4c6bf5-9e7d-44be-b2c3-cc66b6acb1b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='brand-header']/nav/div/div/div[2]/div[3]/div[2]/div/div[2]/span</value>
      <webElementGuid>394b2a15-b1df-4f69-a754-0ad918f49aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anular'])[1]/following::span[4]</value>
      <webElementGuid>82f1b9ad-85f6-47ef-8897-0f35718685f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produto removido'])[1]/following::span[5]</value>
      <webElementGuid>d9a0da1a-8c6d-4180-835b-1c74e22074e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='un'])[2]/preceding::span[1]</value>
      <webElementGuid>44f133bf-d42b-4630-8182-d87fd8e201cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produto removido'])[2]/preceding::span[2]</value>
      <webElementGuid>f0fdd305-2615-4f0b-b49f-0b35ac24280d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/span</value>
      <webElementGuid>fa2d7f3e-4c34-494f-89be-903315e0f193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '€13,37' or . = '€13,37')]</value>
      <webElementGuid>6f58fe98-251a-4b74-9590-8f7acd9838e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
