<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Carrinho_2</name>
   <tag></tag>
   <elementGuidId>a1291198-5737-437d-8f4c-ab9eb7f21eae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='product-search-results']/div/div[2]/div[2]/div/div/div/div/div[2]/div[2]/div[3]/div[2]/button/span[2])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
