<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon-search</name>
   <tag></tag>
   <elementGuidId>8c0b8726-e2a2-48b0-8161-b30fc6eabb58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//span[contains(@class,'icon-search')])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg.svg-inline.icon-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>abc0605c-42e2-4540-8091-c75f6bdb6181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg-inline icon-search</value>
      <webElementGuid>efa36acc-f30c-4a37-9089-26f25bd3a0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>61201e6c-287e-4bc3-9c30-1a328062ad0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>e4599def-2f7d-40b7-82af-5d9ea8403615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>f024415b-6b8f-48bb-b57e-3a143a112c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 20 20</value>
      <webElementGuid>dffe0dc0-b56e-4c31-91d6-d9d69766baef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brand-header&quot;)/nav[@class=&quot;nav-wrapper col-nav-wrapper&quot;]/div[@class=&quot;sticky-element navigation-shadows&quot;]/div[@class=&quot;header-wrapper container-fluid container-margin d-flex align-items-center justify-content-between&quot;]/div[@class=&quot;user-util d-flex align-items-center&quot;]/div[@class=&quot;user-search d-block d-md-none&quot;]/button[@class=&quot;btn no-padding js-open-searchbar&quot;]/span[@class=&quot;svg-wrapper svg-icon-search&quot;]/svg[@class=&quot;svg-inline icon-search&quot;]</value>
      <webElementGuid>cbab8d80-baf5-48ab-82bc-7fa38b3c32bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EntregaZero'])[1]/following::*[name()='svg'][4]</value>
      <webElementGuid>ddaf8b7a-0e14-43d2-81cc-2c6c2c3a9969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Área de entrega'])[1]/following::*[name()='svg'][5]</value>
      <webElementGuid>a24bde26-a211-4847-aedb-fc21276c87f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login/Registo'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>d5eb25e7-8a47-4a83-9a5a-364439de361b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login/Registo'])[2]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>d320822a-d4da-496e-a6c9-46aafd65a8b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
