<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_search_item</name>
   <tag></tag>
   <elementGuidId>2a2dc2c5-86c3-48b0-95b8-6740ba6a2b98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='search-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;search-button&quot;] > span.svg-wrapper.svg-icon-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>139311a1-8e69-42ce-9e44-fc70850678b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg-wrapper svg-icon-search</value>
      <webElementGuid>202a2c3c-6596-407f-8642-342cb43a3335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brand-header&quot;)/nav[@class=&quot;nav-wrapper col-nav-wrapper&quot;]/div[@class=&quot;sticky-element navigation-shadows&quot;]/div[@class=&quot;search-mobile search-shadow&quot;]/form[@class=&quot;global-search-form&quot;]/div[@class=&quot;field-input-label col-field-input-label label-animation&quot;]/div[@class=&quot;search-suggestions-actions&quot;]/button[@class=&quot;search-button&quot;]/span[@class=&quot;svg-wrapper svg-icon-search&quot;]</value>
      <webElementGuid>bebf40e5-13a1-45d9-8927-6c74433602c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='brand-header']/nav/div/div[3]/form/div/div/button/span</value>
      <webElementGuid>eac4d4b0-92fe-4f98-ac45-f69462f40ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O que procura?'])[1]/following::span[1]</value>
      <webElementGuid>51be0ab7-e847-4965-b290-e453d76298b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2023 Modelo Continente Hipermercados, S.A. Todos os direitos reservados'])[1]/following::span[1]</value>
      <webElementGuid>f4c00620-08ba-4cf5-9976-543176ea4a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sugestões Principais'])[1]/preceding::span[2]</value>
      <webElementGuid>a7887328-83cc-4c41-813e-ab6d6bbf70fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Queijo Flamengo Fatiado'])[1]/preceding::span[2]</value>
      <webElementGuid>a93d4497-697c-4ae8-ad25-f5243afeebb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/button/span</value>
      <webElementGuid>46495ecd-6867-453b-93b8-b3748d273532</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
